//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanacHotelaPresentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanacHotelaPresentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Chain.
        /// </summary>
        public static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arragement created..
        /// </summary>
        public static string arragementCreated {
            get {
                return ResourceManager.GetString("arragementCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string arrangementCancelled {
            get {
                return ResourceManager.GetString("arrangementCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled:.
        /// </summary>
        public static string arrangementCancelledInput {
            get {
                return ResourceManager.GetString("arrangementCancelledInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement deleted..
        /// </summary>
        public static string arrangementDeleted {
            get {
                return ResourceManager.GetString("arrangementDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string arrangementEndInput {
            get {
                return ResourceManager.GetString("arrangementEndInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string arrangementFinished {
            get {
                return ResourceManager.GetString("arrangementFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished:.
        /// </summary>
        public static string arrangementFinishedInput {
            get {
                return ResourceManager.GetString("arrangementFinishedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string arrangementFrom {
            get {
                return ResourceManager.GetString("arrangementFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest:.
        /// </summary>
        public static string arrangementGuestInput {
            get {
                return ResourceManager.GetString("arrangementGuestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string arrangementHotel {
            get {
                return ResourceManager.GetString("arrangementHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel:.
        /// </summary>
        public static string arrangementHotelInput {
            get {
                return ResourceManager.GetString("arrangementHotelInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string arrangementName {
            get {
                return ResourceManager.GetString("arrangementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Nights.
        /// </summary>
        public static string arrangementNights {
            get {
                return ResourceManager.GetString("arrangementNights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Price.
        /// </summary>
        public static string arrangementPrice {
            get {
                return ResourceManager.GetString("arrangementPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room ID.
        /// </summary>
        public static string arrangementRoomID {
            get {
                return ResourceManager.GetString("arrangementRoomID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room:.
        /// </summary>
        public static string arrangementRoomInput {
            get {
                return ResourceManager.GetString("arrangementRoomInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string arrangementStartInput {
            get {
                return ResourceManager.GetString("arrangementStartInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string arrangementSurname {
            get {
                return ResourceManager.GetString("arrangementSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string arrangementTo {
            get {
                return ResourceManager.GetString("arrangementTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string buttonAdd {
            get {
                return ResourceManager.GetString("buttonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string buttonDelete {
            get {
                return ResourceManager.GetString("buttonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string buttonUpdate {
            get {
                return ResourceManager.GetString("buttonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ID.
        /// </summary>
        public static string contactContactID {
            get {
                return ResourceManager.GetString("contactContactID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact created..
        /// </summary>
        public static string contactCreated {
            get {
                return ResourceManager.GetString("contactCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact deleted..
        /// </summary>
        public static string contactDeleted {
            get {
                return ResourceManager.GetString("contactDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest ID.
        /// </summary>
        public static string contactGuestID {
            get {
                return ResourceManager.GetString("contactGuestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel ID.
        /// </summary>
        public static string contactHotelID {
            get {
                return ResourceManager.GetString("contactHotelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string contactInfo {
            get {
                return ResourceManager.GetString("contactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info:.
        /// </summary>
        public static string contactInfoInput {
            get {
                return ResourceManager.GetString("contactInfoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string contactType {
            get {
                return ResourceManager.GetString("contactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string contactTypeInput {
            get {
                return ResourceManager.GetString("contactTypeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating failed..
        /// </summary>
        public static string failedCreate {
            get {
                return ResourceManager.GetString("failedCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting failed..
        /// </summary>
        public static string failedDelete {
            get {
                return ResourceManager.GetString("failedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all fields..
        /// </summary>
        public static string fillAll {
            get {
                return ResourceManager.GetString("fillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string financialHotel {
            get {
                return ResourceManager.GetString("financialHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financials.
        /// </summary>
        public static string financialTab {
            get {
                return ResourceManager.GetString("financialTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string financialTotalIncome {
            get {
                return ResourceManager.GetString("financialTotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Nights.
        /// </summary>
        public static string financialTotalNights {
            get {
                return ResourceManager.GetString("financialTotalNights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest created..
        /// </summary>
        public static string guestCreated {
            get {
                return ResourceManager.GetString("guestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest deleted..
        /// </summary>
        public static string guestDeleted {
            get {
                return ResourceManager.GetString("guestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest has arrangements..
        /// </summary>
        public static string guestHasArr {
            get {
                return ResourceManager.GetString("guestHasArr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest ID.
        /// </summary>
        public static string guestsGuestID {
            get {
                return ResourceManager.GetString("guestsGuestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security.
        /// </summary>
        public static string guestsJMBG {
            get {
                return ResourceManager.GetString("guestsJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security:.
        /// </summary>
        public static string guestsJMBGInput {
            get {
                return ResourceManager.GetString("guestsJMBGInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string guestsName {
            get {
                return ResourceManager.GetString("guestsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string guestsNameInput {
            get {
                return ResourceManager.GetString("guestsNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string guestsSurname {
            get {
                return ResourceManager.GetString("guestsSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string guestsSurnameInput {
            get {
                return ResourceManager.GetString("guestsSurnameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string guestsTab {
            get {
                return ResourceManager.GetString("guestsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel created..
        /// </summary>
        public static string hotelCreated {
            get {
                return ResourceManager.GetString("hotelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel deleted..
        /// </summary>
        public static string hotelDeleted {
            get {
                return ResourceManager.GetString("hotelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel has arrangements..
        /// </summary>
        public static string hotelHasArrang {
            get {
                return ResourceManager.GetString("hotelHasArrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string hotelsCity {
            get {
                return ResourceManager.GetString("hotelsCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string hotelsCityInput {
            get {
                return ResourceManager.GetString("hotelsCityInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string hotelsContactInput {
            get {
                return ResourceManager.GetString("hotelsContactInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string hotelsCountry {
            get {
                return ResourceManager.GetString("hotelsCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string hotelsCountryInput {
            get {
                return ResourceManager.GetString("hotelsCountryInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string hotelsHotel {
            get {
                return ResourceManager.GetString("hotelsHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string hotelsNameInput {
            get {
                return ResourceManager.GetString("hotelsNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string hotelsNumber {
            get {
                return ResourceManager.GetString("hotelsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string hotelsNumberInput {
            get {
                return ResourceManager.GetString("hotelsNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string hotelsStars {
            get {
                return ResourceManager.GetString("hotelsStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars:.
        /// </summary>
        public static string hotelsStarsInput {
            get {
                return ResourceManager.GetString("hotelsStarsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string hotelsStreet {
            get {
                return ResourceManager.GetString("hotelsStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        public static string hotelsStreetInput {
            get {
                return ResourceManager.GetString("hotelsStreetInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        public static string hotelsZIP {
            get {
                return ResourceManager.GetString("hotelsZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP:.
        /// </summary>
        public static string hotelsZIPInput {
            get {
                return ResourceManager.GetString("hotelsZIPInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string loginButtonText {
            get {
                return ResourceManager.GetString("loginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string loginLangText {
            get {
                return ResourceManager.GetString("loginLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string loginPassText {
            get {
                return ResourceManager.GetString("loginPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string loginUserText {
            get {
                return ResourceManager.GetString("loginUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logOutButtonText {
            get {
                return ResourceManager.GetString("logOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only contact..
        /// </summary>
        public static string onlyContact {
            get {
                return ResourceManager.GetString("onlyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room created..
        /// </summary>
        public static string roomCreated {
            get {
                return ResourceManager.GetString("roomCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room deleted..
        /// </summary>
        public static string roomDeleted {
            get {
                return ResourceManager.GetString("roomDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room has arrangements..
        /// </summary>
        public static string roomHasArr {
            get {
                return ResourceManager.GetString("roomHasArr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has AC:.
        /// </summary>
        public static string roomsACInput {
            get {
                return ResourceManager.GetString("roomsACInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string roomsFloor {
            get {
                return ResourceManager.GetString("roomsFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor:.
        /// </summary>
        public static string roomsFloorInput {
            get {
                return ResourceManager.GetString("roomsFloorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has AC.
        /// </summary>
        public static string roomsHasAC {
            get {
                return ResourceManager.GetString("roomsHasAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had AC:.
        /// </summary>
        public static string roomsHasACInput {
            get {
                return ResourceManager.GetString("roomsHasACInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has TV.
        /// </summary>
        public static string roomsHasTV {
            get {
                return ResourceManager.GetString("roomsHasTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has TV:.
        /// </summary>
        public static string roomsHasTVInput {
            get {
                return ResourceManager.GetString("roomsHasTVInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string roomsHotel {
            get {
                return ResourceManager.GetString("roomsHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel:.
        /// </summary>
        public static string roomsHotelInput {
            get {
                return ResourceManager.GetString("roomsHotelInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Beds.
        /// </summary>
        public static string roomsNumberOfBeds {
            get {
                return ResourceManager.GetString("roomsNumberOfBeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beds:.
        /// </summary>
        public static string roomsNumberOfBedsInput {
            get {
                return ResourceManager.GetString("roomsNumberOfBedsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string roomsPrice {
            get {
                return ResourceManager.GetString("roomsPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string roomsPriceInput {
            get {
                return ResourceManager.GetString("roomsPriceInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room ID.
        /// </summary>
        public static string roomsRoomID {
            get {
                return ResourceManager.GetString("roomsRoomID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number.
        /// </summary>
        public static string roomsRoomNumber {
            get {
                return ResourceManager.GetString("roomsRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room:.
        /// </summary>
        public static string roomsRoomNumberInput {
            get {
                return ResourceManager.GetString("roomsRoomNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has TV:.
        /// </summary>
        public static string roomsTVInput {
            get {
                return ResourceManager.GetString("roomsTVInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select arrangement..
        /// </summary>
        public static string selectArrangment {
            get {
                return ResourceManager.GetString("selectArrangment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select contact..
        /// </summary>
        public static string selectContact {
            get {
                return ResourceManager.GetString("selectContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select guest..
        /// </summary>
        public static string selectGuest {
            get {
                return ResourceManager.GetString("selectGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select hotel..
        /// </summary>
        public static string selectHotel {
            get {
                return ResourceManager.GetString("selectHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select room..
        /// </summary>
        public static string selectRoom {
            get {
                return ResourceManager.GetString("selectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select employee..
        /// </summary>
        public static string selectZaposleni {
            get {
                return ResourceManager.GetString("selectZaposleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangements.
        /// </summary>
        public static string tabArrangements {
            get {
                return ResourceManager.GetString("tabArrangements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string tabContact {
            get {
                return ResourceManager.GetString("tabContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        public static string tabHotels {
            get {
                return ResourceManager.GetString("tabHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string tabRooms {
            get {
                return ResourceManager.GetString("tabRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries updated..
        /// </summary>
        public static string updated {
            get {
                return ResourceManager.GetString("updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee created..
        /// </summary>
        public static string zaposleniCreated {
            get {
                return ResourceManager.GetString("zaposleniCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee deleted..
        /// </summary>
        public static string zaposleniDeleted {
            get {
                return ResourceManager.GetString("zaposleniDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager:.
        /// </summary>
        public static string zaposleniIsManagerInput {
            get {
                return ResourceManager.GetString("zaposleniIsManagerInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string zaposleniJeMenadzer {
            get {
                return ResourceManager.GetString("zaposleniJeMenadzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string zaposleniPassword {
            get {
                return ResourceManager.GetString("zaposleniPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string zaposleniPasswordInput {
            get {
                return ResourceManager.GetString("zaposleniPasswordInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string zaposleniTab {
            get {
                return ResourceManager.GetString("zaposleniTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string zaposleniUsername {
            get {
                return ResourceManager.GetString("zaposleniUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string zaposleniUsernameInput {
            get {
                return ResourceManager.GetString("zaposleniUsernameInput", resourceCulture);
            }
        }
    }
}
